### PR TITLE
v0.2.11 - Scene library unit tests and fixes

### LINKED ISSUE #127: Scene library unit tests

### PR DESCRIPTION
**Pull request by Kejoko**
- closes #127

### CODE REVIEW

File: src/quartz/physics/collider/Collider.cpp [hunk 1]
```diff
@@ -183,6 +183,21 @@ quartz::physics::Collider::getWorldRotation() const {
     return math::Quaternion(mp_collider->getLocalToWorldTransform().getOrientation()).normalize();
 }
 
+void
+quartz::physics::Collider::setScale(
+    UNUSED const math::Vec3& scale
```
Comment (Kejoko) [inline src/quartz/physics/collider/Collider.cpp:188]: Can get rid of this UNUSED keyword

File: src/quartz/rendering/cube_map/CubeMap.cpp [hunk 2]
```diff
@@ -4,6 +4,7 @@
 
 #include "quartz/rendering/cube_map/CubeMap.hpp"
 #include "quartz/rendering/vulkan_util/VulkanUtil.hpp"
+#include "util/logger/Logger.hpp"
```
Comment (Kejoko) [inline src/quartz/rendering/cube_map/CubeMap.cpp:7]: Fix include order

File: test/unit/quartz/scene/doodad/test_Doodad.cpp [hunk 3]
```diff
@@ -0,0 +1,1453 @@
+#include <cstdint>
+#include <memory>
+#include <optional>
+
+#include "quartz/physics/collider/SphereShape.hpp"
```
Comment (Kejoko) [inline test/unit/quartz/scene/doodad/test_Doodad.cpp:5]: include order

File: test/unit/quartz/scene/light/test_Light.cpp [hunk 4]
```diff
@@ -0,0 +1,53 @@
+#include "math/transform/Vec3.hpp"
```
Comment (Kejoko) [inline test/unit/quartz/scene/light/test_Light.cpp:1]: space

File: test/unit/quartz/scene/sky_box/test_SkyBox.cpp [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+#include "util/logger/Logger.hpp"
+#include "util/unit_test/UnitTest.hpp"
+
+#include "quartz/rendering/buffer/StagedImageBuffer.hpp"
+#include "quartz/rendering/cube_map/CubeMap.hpp"
+#include "quartz/rendering/device/Device.hpp"
+#include "quartz/rendering/instance/Instance.hpp"
+#include "quartz/scene/sky_box/SkyBox.hpp"
+#include <cstring>
+#include <vulkan/vulkan_handles.hpp>
```
Comment (Kejoko) [inline test/unit/quartz/scene/sky_box/test_SkyBox.cpp:11]: fix these includes

File: assets
Comment (Kejoko) [inline assets:1]: make sure to merge this to assets's master branch first

**Review by Kejoko — COMMENTED** [review]
Fix some things before we merge
